services:
  ragchatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ragchatbot
    ports:
      - "8007:8007"
    depends_on:
      - ollama
    volumes:
      - .:/app"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
