services:
  ollama:
    build:
      context: ./docker-ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
  ragchatbot:
    build:
      context: ./docker-ragchatbot
      dockerfile: Dockerfile
    container_name: ragchatbot
    ports:
      - "8007:8007"
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=ics'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
